@baseurl = https://h74dp9tg-3978.brs.devtunnels.ms


### Post NotifyFollowUpStart
POST {{baseurl}}/api/notifyFollowUpStart
Content-Type: application/json

{
    "name": "Mateus epifanio linhares",
    "email": "mlinhares@softexpert.com"
}